"""Parsers for the reports produced by each pipeline stage.

Every parser returns ``None`` when its report is missing, so a failed or
skipped stage never breaks metric collection.
"""

from __future__ import annotations

import json
import xml.etree.ElementTree as ET  # nosec B405 - parses reports generated by our own pipeline
from pathlib import Path

SEVERITIES = ("critical", "high", "medium", "low", "unknown")


def find_report(root: Path, name: str) -> Path | None:
    """Return the first file called ``name`` anywhere under ``root``."""
    if not root.exists():
        return None
    direct = root / name
    if direct.is_file():
        return direct
    return next(iter(sorted(root.rglob(name))), None)


def load_json(path: Path | None):
    if path is None:
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def parse_junit(path: Path | None) -> dict | None:
    if path is None:
        return None
    root = ET.parse(path).getroot()  # nosec B314
    suites = [root] if root.tag == "testsuite" else root.findall("testsuite")
    totals = {"total": 0, "failed": 0, "errors": 0, "skipped": 0, "duration_seconds": 0.0}
    for suite in suites:
        totals["total"] += int(suite.get("tests", 0))
        totals["failed"] += int(suite.get("failures", 0))
        totals["errors"] += int(suite.get("errors", 0))
        totals["skipped"] += int(suite.get("skipped", 0))
        totals["duration_seconds"] += float(suite.get("time", 0.0))
    totals["passed"] = totals["total"] - totals["failed"] - totals["errors"] - totals["skipped"]
    totals["duration_seconds"] = round(totals["duration_seconds"], 3)
    return totals


def parse_coverage(path: Path | None) -> dict | None:
    if path is None:
        return None
    root = ET.parse(path).getroot()  # nosec B314
    return {
        "line_rate": round(float(root.get("line-rate", 0.0)), 4),
        "branch_rate": round(float(root.get("branch-rate", 0.0)), 4),
    }


def parse_bandit(path: Path | None) -> dict | None:
    data = load_json(path)
    if data is None:
        return None
    counts = {"high": 0, "medium": 0, "low": 0}
    for issue in data.get("results", []):
        severity = str(issue.get("issue_severity", "")).lower()
        if severity in counts:
            counts[severity] += 1
    return counts


def parse_pip_audit(path: Path | None) -> dict | None:
    data = load_json(path)
    if data is None:
        return None
    dependencies = data.get("dependencies", []) if isinstance(data, dict) else data
    vulnerable = []
    total = 0
    for dep in dependencies:
        vulns = dep.get("vulns", [])
        if vulns:
            total += len(vulns)
            vulnerable.append(
                {"name": dep.get("name"), "version": dep.get("version"), "ids": [v.get("id") for v in vulns]}
            )
    return {"vulnerabilities": total, "packages": vulnerable}


def parse_trivy(path: Path | None) -> dict | None:
    data = load_json(path)
    if data is None:
        return None
    counts = dict.fromkeys(SEVERITIES, 0)
    critical_fixable = 0
    for result in data.get("Results", []) or []:
        for vuln in result.get("Vulnerabilities", []) or []:
            severity = str(vuln.get("Severity", "unknown")).lower()
            counts[severity if severity in counts else "unknown"] += 1
            if severity == "critical" and vuln.get("FixedVersion"):
                critical_fixable += 1
    counts["critical_fixable"] = critical_fixable
    return counts


def parse_ruff(path: Path | None) -> dict | None:
    data = load_json(path)
    if data is None:
        return None
    return {"issues": len(data)}
